### ISSUE TITLE
Proposing an alternate way of checking whether it's an Object or not

### ISSUE THREAD

**Issue by AmaanKulshreshtha** [jonschlinkert/isobject#18]
The following code:

```javascript
const isObject = obj => Object.prototype.toString.call(obj) === '[object Object]'
```

Advantage: Uses less number of operations to detect if given value is an object or not ✌️

**Comment by jonschlinkert** [comment]
> Advantage: Uses less number of operations to detect if given value is an object or not

In the past, this was benchmarked and it's slower. Also, `Object.prototype.toString` should be declared as a variable outside of that function, otherwise the prototype method can be overridden.

**Comment by AmaanKulshreshtha** [comment]
> In the past, this was benchmarked and it's slower.
Checked the results on jsperf and DAAAAAYYUUUMMM....I didn't expect the former method to be so much slower. It was just funny. 😂 

Closing the issue because the point has been proven ✌️
