### ISSUE TITLE
SEMVER publishing

### ISSUE THREAD

**Issue by crobinson42** [jonschlinkert/isobject#19]
What was the reason for 3.0.1 major bump to 4.0.0?

I don't see release changelog or a CHANGELOG.md in the repo that explains any BREAKING CHANGES which would help explain the version changes.

Perhaps https://www.npmjs.com/package/commitizen would be a benefit to this lib :-)

**Comment by TrySound** [comment]
https://github.com/jonschlinkert/isobject/releases/tag/4.0.0
