### ISSUE TITLE
suggestion: why Array.isArray(val) === false?

### ISSUE THREAD

**Issue by manferlo81** [jonschlinkert/isobject#20]
I noticed you are using `Array.isArray(val) === false`...
https://github.com/jonschlinkert/isobject/blob/ae2b5ea154afc91c02429f44009163ec1850b3c4/index.js#L9
doesn't it make more sense...
```javascript
return val != null && typeof val === 'object' && !Array.isArray(val);
```
or even...
```javascript
return !!val && typeof val === 'object' && !Array.isArray(val);
```
I noticed you used that way here...
https://github.com/jonschlinkert/use/blob/843c0e1b6934cef9570e7a9962501bf84212c3b5/index.js#L146
It's shorter and imho more descriptive. Just a suggestion though.
Happy to do a pr is needed.
Thanks.

**Comment by jonschlinkert** [comment]
> doesn't it make more sense...

No, strict equality is more performant.
