### ISSUE TITLE
breaking change in 1.0.1

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/isobject#4]
that hurts, lol. that `1.0.1` was breaking change really. 
Whole week cant realize why builds of `is-kindof` fails, even released before latest tag that works.

https://travis-ci.org/tunnckoCore/is-kindof/builds see that last `v2.1.0` rebuild fails

It's because `is-kindof` sits on [is-typeof-error](tunnckoCore/is-typeof-error) which use `isobject`. I will update them, but yea.

**Comment by jonschlinkert** [comment]
what breaking change are you referring to?

**Comment by tunnckoCore** [comment]
that change https://github.com/jonschlinkert/isobject/commit/9ae6aafc6276cfafcafecaaf04276cf9b1783854

**Comment by jonschlinkert** [comment]
thanks for staying on top of it. I've reverted and published 1.0.2.

**Comment by tunnckoCore** [comment]
> thanks for staying on top of it. I've reverted and published 1.0.2.

Wasn't needed. I just wanted to mention that was breaking change so it should be `1.1.0`, not `1.0.1`
And I just switched to `is-extendable`.
